dotanuki-labs/norris

buildSrc/src/main/kotlin/Libraries.kt
Bumps **kotlinx.coroutines** to `1.4.1`
- https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.4.1
N/A
=> Bump kotlinx.coroutines to 1.4.1

buildSrc/src/main/kotlin/BuildPlugins.kt
Bumps Detekt 1.4.12
https://github.com/detekt/detekt/releases/tag/v1.14.2
N/A
=> Bumps Detekt to 1.4.12

gradle/wrapper/gradle-wrapper.properties
Self-explained
https://docs.gradle.org/6.8-rc-1/release-notes.html
=> Bumps Gradle to 6.8-rc-1

.github/workflows/main.yml, gradle.properties
- Forces `static_analysis` and `unit_tests` as requirements for `acceptance_tests` in the pipeline
- Force Jacoco out-of-the-process
https://github.com/gradle/gradle/issues/9221#issuecomment-640316310
=> Improves GHA Workflow

features/onboarding/build.gradle.kts, features/onboarding/src/main/java/io/dotanuki/norris/onboarding/OnboardingActivity.kt, features/onboarding/src/main/java/io/dotanuki/norris/onboarding/OnboardingScreenState.kt, features/onboarding/src/main/java/io/dotanuki/norris/onboarding/OnboardingViewModel.kt, features/onboarding/src/main/java/io/dotanuki/norris/onboarding/di/onboardingModule.kt, features/onboarding/src/test/java/io/dotanuki/norris/onboarding/OnboardingViewModelTests.kt
Self-explained
Follow-up of #32 
N/A
=> Refactored on-boarding screen on top of StateFlow

features/facts/src/main/java/io/dotanuki/norris/facts/di/factsModule.kt, features/onboarding/src/main/java/io/dotanuki/norris/onboarding/di/onboardingModule.kt, features/search/src/main/java/io/dotanuki/norris/search/di/searchModule.kt
=> Applied supress for warnings and instantiate things lazily on Kodein modules

gradle/wrapper/gradle-wrapper.properties
Self-explained
https://docs.gradle.org/6.8/release-notes.html
N/A
=> Bumps Gradle to 6.8

.github/workflows/main.yml
=> Improved triggers for Main Workflow

gradle/wrapper/gradle-wrapper.properties
=> Bumps Gradle to 6.8.3

.mergify.yml
=> Requiring approval for PRs opened by Dependabot

.mergify.yml
=> Setting up mergebot account

features/facts/build.gradle.kts, features/onboarding/build.gradle.kts, features/search/build.gradle.kts, platform/coroutines-testutils/build.gradle.kts, platform/domain/build.gradle.kts, platform/networking/build.gradle.kts, platform/persistance/build.gradle.kts, platform/rest-chucknorris/build.gradle.kts
=> Bumps kotlinx.coroutines from 1.4.1 to 1.4.3

.mergify.yml
=> Improving interactions for merging bot

.mergify.yml
=> Updating mergebot rules

.github/workflows/main.yml, .mergify.yml
=> Pinning versions for GHA runners

README.md, scripts/emulate-pr-build.sh
=> Moving CI emulation script to scripts dir

.github/workflows/main.yml
Self-explained
Follow-up from #108.
=> Bumping actions/setup-java to 2.0.0

.mergify.yml
=> Updating config for mergebot

app/build.gradle.kts, settings.gradle.kts
Self-explained. Closes #164  
Added google Maven repository as part of plugin management
=> Bumps keeper plugin to 0.10.0

.mergify.yml
=> Integrating dotanukibot with mergify

app/src/main/java/io/dotanuki/demos/norris/DependenciesSetup.kt, app/src/main/java/io/dotanuki/demos/norris/di/applicationModule.kt, features/facts/src/main/java/io/dotanuki/norris/facts/di/factsModule.kt, features/onboarding/src/main/java/io/dotanuki/norris/onboarding/di/onboardingModule.kt, features/search/src/main/java/io/dotanuki/norris/search/di/searchModule.kt, platform/navigator/src/main/java/io/dotanuki/norris/navigator/di/navigatorModule.kt, platform/persistance/src/main/java/io/dotanuki/norris/persistance/di/persistanceModule.kt, platform/rest-chucknorris/src/main/java/io/dotanuki/norris/rest/di/restInfrastructureModule.kt
=> Moves Kodein modules to the new bind API

.github/workflows/main.yml
=> Spliting CI cache entries per Job

app/src/androidTest/java/io/dotanuki/demos/norris/NorrisAcceptanceTests.kt, features/facts/src/main/java/io/dotanuki/norris/facts/presentation/FactsViewModel.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsActivity.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/SharingHelper.kt, features/facts/src/test/java/io/dotanuki/norri/facts/FactsIntegrationTests.kt, features/facts/src/test/java/io/dotanuki/norri/facts/FactsPresentationTests.kt, features/search/src/main/java/io/dotanuki/norris/search/presentation/SearchViewModel.kt, features/search/src/main/java/io/dotanuki/norris/search/ui/SearchActivity.kt, features/search/src/main/java/io/dotanuki/norris/search/ui/SearchViewDelegate.kt, features/search/src/test/java/io/dotanuki/norris/search/tests/SearchIntegrationTests.kt, platform/testing-rest/src/main/java/io/dotanuki/testing/rest/RestDataBuilder.kt
=> Improving integration tests readability

.github/workflows/main.yml, scripts/aggregate-test-reports.sh
- Implements aggregation script
- Optionally generates aggregated report with [xunit-viewer](https://github.com/lukejpreston/xunit-viewer)
N/A
=> Better approach for junit reports

features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsActivity.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsScreen.kt, features/search/src/main/java/io/dotanuki/norris/search/ui/SearchActivity.kt, features/search/src/main/java/io/dotanuki/norris/search/ui/SearchScreen.kt, platform/shared-utilities/src/main/java/io/dotanuki/norris/features/utilties/extensions_activity.kt
=> Refactored screen delegates

features/facts/src/test/java/io/dotanuki/norri/facts/FactsIntegrationTests.kt, features/facts/src/test/resources/robolectric.properties, features/search/src/test/java/io/dotanuki/norris/search/tests/SearchIntegrationTests.kt, features/search/src/test/resources/robolectric.properties, platform/testing-app/src/main/java/io/dotanuki/testing/app/TestApplication.kt
=> Defines configuration files for Robolectric tests

.github/githubci-gradle.properties, .github/workflows/main.yml
=> Defining new JVM memory settings no CI builds

.github/workflows/main.yml, settings.gradle.kts
=> Reverting to old CI caching approach

buildSrc/src/main/kotlin/configs/AndroidConfig.kt
=> Bumps minSDK version to 25

app/src/androidTest/java/io/dotanuki/demos/norris/NorrisAcceptanceTests.kt
Self-explained
Just leverage what Barista already offers. Each test will run 5 times (as per the default of `@Repeat`)
=> Stressing executions on Espresso tests

features/facts/build.gradle.kts, features/onboarding/build.gradle.kts, features/search/build.gradle.kts
Self-explained
Not longer used
=> Removes turbine from test dependencies

features/facts/build.gradle.kts, features/facts/src/test/java/io/dotanuki/norri/facts/FactsDataSourceTests.kt, features/facts/src/test/resources/200_search_with_results.json, features/search/build.gradle.kts, features/search/src/test/java/io/dotanuki/norris/search/tests/SearchQueryValidationTests.kt, platform/networking/build.gradle.kts, platform/networking/src/test/java/io/dotanuki/norris/networking/HttpIntegrationErrorTransformerTests.kt, platform/networking/src/test/java/io/dotanuki/norris/networking/NetworkingErrorTransformerTests.kt, platform/networking/src/test/java/io/dotanuki/norris/networking/SerializationErrorTransformerTests.kt, platform/rest-chucknorris/build.gradle.kts, platform/rest-chucknorris/src/test/java/io/dotanuki/norris/rest/ManagedExecutionTests.kt
=> Removes burster dependency from tests

.github/githubci-gradle.properties, gradle.properties
=> Tweaking execution over JDK11

app/build.gradle.kts, features/facts/build.gradle.kts, features/onboarding/build.gradle.kts, features/search/build.gradle.kts, platform/logger/build.gradle.kts, platform/navigator/build.gradle.kts, platform/networking/build.gradle.kts, platform/rest-chucknorris/build.gradle.kts, platform/shared-utilities/build.gradle.kts, platform/testing-commons/build.gradle.kts
Self-explained
Now it is added by default by the language plugin for Gradle
=> Removes explicit dependency declaration on kotlin-stdlib

.github/workflows/main.yml, build.gradle.kts, buildSrc/src/main/kotlin/BuildPlugins.kt, detekt.yml, scripts/emulate-pr-build.sh
=> Re-configure detekt on CI

app/build.gradle.kts, build.gradle.kts
=> Removes references to jitpack

app/build.gradle.kts, buildSrc/src/main/kotlin/plugins/KotlinTasksConfiguration.kt, features/facts/src/main/java/io/dotanuki/norris/facts/presentation/RepeatOnLifecycle.kt, platform/networking/src/main/java/io/dotanuki/norris/networking/RetrofitBuilder.kt, platform/testing-commons/src/main/java/io/dotanuki/testing/coroutines/CoroutinesTestHelper.kt
=> Annotates proper classes with Kotlin @optin

.gitignore, gradle.properties
=> Optimising executions of AGP

.github/workflows/main.yml, .mergify.yml, app/build.gradle.kts, buildSrc/src/main/kotlin/versioning.kt
=> Opt-out from deprecated Gradle API

features/search/src/test/java/io/dotanuki/norris/search/tests/SearchDataSourceTests.kt
=> Revamped  data layer tests for Search

buildSrc/src/main/kotlin/versioning.kt
=> Release 2.0.0

features/facts/src/test/java/io/dotanuki/norris/facts/FactsActivityTests.kt, features/facts/src/test/java/io/dotanuki/norris/facts/FactsDataSourceTests.kt, features/facts/src/test/java/io/dotanuki/norris/facts/FactsPresentationTests.kt, features/facts/src/test/java/io/dotanuki/norris/facts/util/FakeFactsScreen.kt, features/facts/src/test/java/io/dotanuki/norris/facts/util/factsTestModule.kt, features/search/src/test/java/io/dotanuki/norris/search/SearchActivityTests.kt, features/search/src/test/java/io/dotanuki/norris/search/SearchDataSourceTests.kt, features/search/src/test/java/io/dotanuki/norris/search/SearchQueryValidationTests.kt, features/search/src/test/java/io/dotanuki/norris/search/util/FakeSearchScreen.kt, features/search/src/test/java/io/dotanuki/norris/search/util/searchTestModule.kt
=> Making testing packages follow standard names on feature modules

scripts/espresso-run.sh
=> Logs execution results from acceptance tests at CI

scripts/emulate-pr-build.sh, scripts/espresso-run.sh
Self-explained
- She-banging properly
- Echoing less
- Echoing better
=> Improving companion scripts

app/build.gradle.kts, scripts/espresso-run.sh
Self-explained
- Moduralised some test mode detection logic
- Improved logs on CI
=> Improving builds running with test mode

app/build.gradle.kts, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsActivity.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsRecyclerAdapter.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsScreen.kt
=> Sharing text and url for a Chuck Norris fact

README.md
=> Added more details about current testing approach

README.md
=> Updates statistics about testing strategy

.github/workflows/main.yml, .mergify.yml
=> Refactor CI topology to speed-up Workflow executions

README.md, scripts/emulate-pr-build.sh
=> Added more stuff around building and running docs

features/facts/build.gradle.kts, features/search/build.gradle.kts
=> Removes dependency on Fragments artefact

.github/workflows/main.yml, README.md, platform/rest-chucknorris/build.gradle.kts, platform/rest-chucknorris/src/main/java/io/dotanuki/norris/rest/rawModels.kt, platform/rest-chucknorris/src/test/java/io/dotanuki/norris/rest/ExpectedErrorsContractTests.kt, platform/rest-chucknorris/src/test/java/io/dotanuki/norris/rest/ExpectedSuccessesContractTests.kt, platform/testing-rest/src/main/java/io/dotanuki/testing/rest/ChuckNorrisApi.kt
Self-explained
- Used the existing integration with `junit`
- Archiving Pacts as build artefacts
=> Implemented contract tests on top of Pact

app/build.gradle.kts, build.gradle.kts, buildSrc/build.gradle.kts, features/facts/build.gradle.kts, features/search/build.gradle.kts, gradle.properties
Self-explained
Previously* blocked by https://github.com/Karumi/Shot/issues/247
- Closes #267
- Closes #269  
- Closes #270
- Closes #271
=> Bumping AGP to 7.0.0

app/build.gradle.kts, buildSrc/src/main/kotlin/plugins/AndroidLibraryConfiguration.kt
=> Removing usages of deprecated AGP DSLs

proguard/logs.pro
=> Added Proguard rules to remove logs from final APK

gradle.properties
Self-explained
This functionality is now provided by `android.nonTransitiveRClass` which is already in-place
=> Removes deprecated Gradle property

.github/workflows/main.yml, app/build.gradle.kts, buildSrc/src/main/kotlin/configs/KotlinConfig.kt, buildSrc/src/main/kotlin/plugins/AndroidLibraryConfiguration.kt
Self-explained
Possible after #268
=> Compiling using java11 bytecode

.github/dependabot.yml
=> Increasing limit for PRs raised by  Dependabot

README.md
=> Added note about JDK11 in the local setup

gradle.properties
Self-explained
This behaviour will become default on AGP8.0.0
=> Forcing r8 to fail on missing classes

scripts/aggregate-test-reports.sh, scripts/emulate-pr-build.sh, scripts/espresso-run.sh, scripts/secrets.sh
Self-explained
- Applied `shfmt` to all scripts
- Applied `shellcheck` to all scripts
=> Improving quality of companion scripts

buildSrc/src/main/kotlin/conventions/KotlinProjectConventions.kt
=> Suppress warnings about Retrofit during test execution

app/build.gradle.kts
Self-explained
Removes related warning during build
N/A
=> Applies variant filter for keeper plugin

.github/dependabot.yml
Self-explained
Forces **dependabot** to scan `buildSrc/build.gradle.kts`
=> Let Dependabot monitor dependencies on buildSrc

app/build.gradle.kts, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt
Self-explained
Implemented with [leak-canary support for release builds](https://square.github.io/leakcanary/recipes/#leakcanary-in-release-builds)
=> Detecting memory leaks during acceptance tests

buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt, buildSrc/src/main/kotlin/conventions/TestModeConventions.kt
Self-explained
Refactors code related to conventions and get rid of all private extensions functions that were used only in one place
=> Re-organises code for Android app shared conventions

app/build.gradle.kts, app/src/androidTest/java/io/dotanuki/demos/norris/NorrisAcceptanceTests.kt, app/src/androidTest/java/io/dotanuki/demos/norris/ScreenRobot.kt, build.gradle.kts
Self-explained
Possible after https://github.com/AdevintaSpain/Barista/issues/382 solved
=> Bumps Barista to 4.0.0 and ditches jcenter usages

.editorconfig, .github/actions/setup-android-build/setup-gradle-properties.sh, scripts/aggregate-test-reports.sh, scripts/ci-tasks.sh, scripts/espresso-run.sh, scripts/secrets.sh
=> Standard formatting for all Shell scripts

app/build.gradle.kts
Self-explained
Closes #313 
We have to fix an issue about `org.checkerframework` being duplicated in the classpath as part of this update, as it seems
=> Bumps Barista to 4.1.0

app/build.gradle.kts, features/facts/build.gradle.kts, features/onboarding/build.gradle.kts, features/search/build.gradle.kts, platform/common/common-android/build.gradle.kts, platform/core/core-navigator/build.gradle.kts, platform/core/core-rest/build.gradle.kts, platform/testing/testing-app/build.gradle.kts, platform/testing/testing-persistance/build.gradle.kts, platform/testing/testing-rest/build.gradle.kts, settings.gradle.kts
Self-explained
Based in [this experimental features available at Gradle 7.x](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors)
=> Ditches hardcoded strings with type-safe accessors on Gradle scripts

build.gradle.kts, platform/core/core-rest/src/test/java/io/dotanuki/norris/rest/ExpectedErrorsContractTests.kt, platform/core/core-rest/src/test/java/io/dotanuki/norris/rest/ExpectedSuccessesContractTests.kt
=> Fixes formatting and bumps ktlint to 10.2.0

build.gradle.kts, buildSrc/build.gradle.kts
Self-explained
- Closes #329 
- Closes #330 
- Closes #331
=> Bumps kotlin to 1.5.31

features/facts/build.gradle.kts, features/onboarding/build.gradle.kts, features/search/build.gradle.kts, platform/common/common-android/build.gradle.kts, platform/core/core-networking/build.gradle.kts, platform/core/core-persistance/build.gradle.kts, platform/core/core-rest/build.gradle.kts, platform/testing/testing-commons/build.gradle.kts, platform/testing/testing-persistance/build.gradle.kts
Self-explained
- Closes #319
- Closes #320
- Closes #321
- Closes #322
=> Bumps kotlinx.coroutines libraries to 1.5.2

.github/actions/setup-android-build/setup-gradle-properties.sh, gradle.properties
Self-explained. Experimenting with the improved JVM arguments support as per [Kotlin 1.5.30 release](https://blog.jetbrains.com/kotlin/2021/08/kotlin-1-5-30-released/#gradle)
N/A
=> Using custom JVM args for Kompiler daemon

.github/actions/setup-android-build/action.yml
=> Using Azul Zulu as JDK distro for CI builds

app/build.gradle.kts, features/facts/build.gradle.kts, features/search/build.gradle.kts, platform/core/core-networking/build.gradle.kts, platform/core/core-rest/build.gradle.kts, platform/testing/testing-app/build.gradle.kts, platform/testing/testing-rest/build.gradle.kts
Self-explained
- Closes #343 
- Closes #344 
- Closes #345
=> Bumps OkHttp libraries to 4.9.2

build.gradle.kts
=> Inspecting builds with Gradle Doctor

.github/workflows/main.yml, build.gradle.kts
Self-explained
Also saving metrics from CI builds for post-processing purposes
=> Captures build metrics with Talaoit plugin

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/conventions/KotlinProjectConventions.kt
Self-explained
We make it sure that both compilation under `buildSrc` and the overall project follows compatibility with JDK11 for both `kotlinCompile` and `javaCompile` tasks
=> Adds supports for builds with JDK17

build.gradle.kts, buildSrc/build.gradle.kts
Self-explained
- Closes #398
- Closes #399 
- Closes #400
=> Bumps Kotlin Gradle plugins to 1.6.0

.github/workflows/main.yml, .mergify.yml
=> Re-enables screenshot tests on CI

buildSrc/build.gradle.kts
=> Improving dependencies centralised on buildSrc

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/plugins/NorrisAndroidApplicationModulePlugin.kt, buildSrc/src/main/kotlin/plugins/NorrisAndroidFeatureModulePlugin.kt, buildSrc/src/main/kotlin/plugins/NorrisAndroidPlatformModulePlugin.kt, buildSrc/src/main/kotlin/plugins/NorrisKotlinModulePlugin.kt
=> Improves configuration for Ktlint and Detekt

buildSrc/src/main/kotlin/conventions/TestLoggerConventions.kt
Self-explained
Opts into parallel execution with test logger plugin
=> Improves execution of unit tests

.github/workflows/main.yml, app/build.gradle.kts, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt, buildSrc/src/main/kotlin/plugins/NorrisAndroidApplicationModulePlugin.kt
Applies [sonatype-nexus-community/scan-gradle-plugin](https://github.com/sonatype-nexus-community/scan-gradle-plugin) and scan project dependencies for Security issues
N/A
=> Scanning project dependencies with OSSAudit

buildSrc/build.gradle.kts
Self-explained
- Closes #411
- Closes #412
- Closes #413
=> Bumps squareup:okhttp3 to 4.9.3

build.gradle.kts, buildSrc/src/main/kotlin/conventions/OssIndexConventions.kt
=> Added conventions for OSSIndex scanning

.github/actions/setup-android-build/action.yml
- Updates `actions/setup-java` to 2.4.0
- Updates `actions/cache` to 2.1.7
N/A
=> Updates Github Actions nested in setup-android-build

buildSrc/build.gradle.kts
Self-explained
- Closes #429 
- Closes #430
=> Bumps shot to 5.12.0

.mergify.yml
Self-explained
Possible after [this announcement](https://github.blog/changelog/2021-11-30-github-actions-workflows-triggered-by-dependabot-receive-dependabot-secrets/)
=> Merging automatically successful PRs from Dependabot

.github/workflows/main.yml, build.gradle.kts, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt, gradle.properties
Self-explained
Also reports metrics to [codecov.io](https://codecov.io)
=> Integrates kotlin-kover for test coverage

.github/workflows/main.yml
=> Updates archive name for test reports

.github/workflows/main.yml, app/src/main/AndroidManifest.xml, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt
=> Running instrumentation tests with coverage

.github/workflows/main.yml, app/src/main/AndroidManifest.xml, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt
Reverts dotanuki-labs/norris#461
=> Revert "Running instrumentation tests with coverage"

.mergify.yml
=> Enforcing security checks when auto-merging

.github/workflows/main.yml, scripts/aggregate-test-reports.sh
Self-explained
Implemented in order to have all executions available for [Thundra Foresight](https://foresight.thundra.io/)
=> Aggregating test reports from all pipelines

buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt, buildSrc/src/main/kotlin/conventions/KotlinProjectConventions.kt
Outcome from #467
This configuration plays better with 3rd party plugins/tools who rely on Java agents
=> Appending JVM args on test tasks by convention

app/build.gradle.kts, app/src/androidTest/java/io/dotanuki/demos/norris/NorrisAcceptanceTests.kt, app/src/androidTest/java/io/dotanuki/demos/norris/PrettyEspressoErrors.kt, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt
=> Makes Espresso errors pretty with Radiography

buildSrc/src/main/kotlin/conventions/OssIndexConventions.kt
Caught by OSS Audit [here](https://github.com/dotanuki-labs/norris/actions/runs/1696997564) 
N/A
=> Ignores vulnerability report on Android Lint dependency

.github/actions/setup-android-build/action.yml
=> Bumps actions/setup-java to v2.5.0

.github/workflows/main.yml
=> Always archive test reports on CI

app/proguard/kodein.pro, buildSrc/build.gradle.kts
Self-explained
- Closes #480 
At #480 the pipeline spotted an issue with obfuscation for some type from `kodein-type` library, that underpins `kode-in`. We apply custom rules - as per suggested in the [related issue](https://github.com/Kodein-Framework/Kodein-DI/issues/309) - to work-around that
=> Bumps android-gradle-plugin to 7.1.0

build.gradle.kts
Self-explained
- https://issuetracker.google.com/issues/216364005
=> Temporary disables GDoctor failures due AS issue with envvars

gradle-updates.toml
=> Adds config for automated Gradle bumps

gradle-updates.toml
Reverts dotanuki-labs/norris#528
=> Revert "Adds config for automated Gradle bumps"

.github/workflows/main.yml, build.gradle.kts
=> Removes test coverage tooling from the project

.github/workflows/main.yml
=> Cleaning-up GHA workflow

app/proguard/kotlin.pro
Details [here](https://www.guardsquare.com/blog/eliminating-data-leaks-caused-by-kotlin-assertions)
N/A
=> Adds proguard rules for Kotlin intrinsics

.github/workflows/main.yml
Implementing this since the previous approach for analyzing tests with Foresight was decommissioned
More [here](https://foresight.docs.thundra.io/advanced-configuration/test-kit)
=> Implements testkit GHA for Foresight

.github/workflows/main.yml, .gitignore, build.gradle.kts
Generating a SBOM for this product for every build
N/A
=> Improves security checks and stores related SBOM

app/build.gradle.kts, app/proguard/kotlin.pro, app/src/androidTest/java/io/dotanuki/demos/norris/test/ChipGroupContentAssertion.kt, app/src/androidTest/java/io/dotanuki/demos/norris/test/NorrisAcceptanceTests.kt, app/src/androidTest/java/io/dotanuki/demos/norris/test/PrettyEspressoErrors.kt, app/src/androidTest/java/io/dotanuki/demos/norris/test/ScreenRobot.kt, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt, buildSrc/src/main/kotlin/conventions/KotlinProjectConventions.kt, features/facts/build.gradle.kts, features/facts/src/androidTest/java/io/dotanuki/norris/facts/test/FactsScreenshotTests.kt, features/facts/src/androidTest/java/io/dotanuki/norris/facts/test/FactsTestActivity.kt, features/search/build.gradle.kts, features/search/src/androidTest/java/io/dotanuki/norris/search/test/SearchScreenshotTests.kt, features/search/src/androidTest/java/io/dotanuki/norris/search/test/SearchTestActivity.kt, platform/common/common-android/build.gradle.kts, platform/core/core-navigator/build.gradle.kts, platform/core/core-persistance/build.gradle.kts, platform/core/core-rest/build.gradle.kts, platform/testing/testing-app/build.gradle.kts, platform/testing/testing-persistance/build.gradle.kts, platform/testing/testing-rest/build.gradle.kts, scripts/ci-tasks.sh
Self-explained. Unfortunately bumping Kotlin to a next major is now a huge PITA 🤦‍♂️
We also had to hack around Keeper plugin with a temp. solution because of Kotlin binary compatibility checks
- Closes #574 
- Closes #571 
- Closes #564 
- Closes #563 
- Closes #487
=> Changes Gradle build setup and bumps Kotlin to v1.7.10

.github/workflows/main.yml
Follow-up from #578 
Sets module name as the prefix of the archived zip, otherwise they won't be collected during `test-results-analysis` job
=> Fixes convention name for screenshot tests archive

.github/renovate.json
=> Adds config for renovate

.github/renovate.json
=> Improves renovate config

.github/actions/setup-android-build/action.yml
- Closes #592 
- Closes #593 
N/A
=> Updates GH actions used in internal steps

buildSrc/src/main/kotlin/definitions/AndroidDefinitions.kt
=> Bumps targetSdk to 32

.mergify.yml
=> Updates mergify configuration with renovate

.github/renovate.json
=> Restricts renovate to Gradle deps

.github/workflows/main.yml
=> Re-pinning GHA with major.minor.patch

app/src/androidTest/java/io/dotanuki/demos/norris/test/NorrisAcceptanceTests.kt, app/src/main/AndroidManifest.xml, app/src/main/java/io/dotanuki/demos/norris/di/applicationModule.kt, buildSrc/src/main/kotlin/conventions/AndroidProjectConventions.kt
Using [mocklab.io](https://mocklab.io) as Mock server for acceptance tests
=> Using online mockserver for acceptance tests

features/facts/src/main/java/io/dotanuki/norris/facts/di/factsModule.kt, features/search/src/main/java/io/dotanuki/norris/search/di/searchModule.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/conventions/KotlinModuleConventions.kt
Also enforces errors on new compilation warnings
N/A
=> Fixes compilation warnings

.github/workflows/main.yml, gradle.properties
=> Improves default configuration for build environment

app/src/androidTest/java/io/dotanuki/demos/norris/test/NorrisAcceptanceTests.kt
=> Removes stress strategy for acceptance tests

scripts/static-analysis.sh
=> Fix formatting for script

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/AndroidDefinitions.kt
=> Updates android-build-tools to 33.0.0

gradle/plugins/settings.gradle.kts, settings.gradle.kts
Self-explained. Removes another build warning
N/A
=> Defines root project name on each settings.gradle file

app/src/main/AndroidManifest.xml
=> Enforces HTTPs-only networking trafic

features/facts/src/main/java/io/dotanuki/norris/facts/di/factsModule.kt
=> Following idiomatic VM factory API

app/src/main/java/io/dotanuki/demos/norris/SplashActivity.kt, app/src/main/res/layout/activity_splash.xml, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsRecyclerAdapter.kt, features/facts/src/main/res/layout/list_item_fact.xml
=> Skipping un-needed ViewBinding generation

gradle.properties
=> Disallows deps resolution during Gradle configuration phase

gradle.properties
As per [this annoucement](https://blog.jetbrains.com/kotlin/2022/07/a-new-approach-to-incremental-compilation-in-kotlin/)
N/A
=> Opt-in for new Kotlin incremental compilation

.github/workflows/main.yml
=> Reporting test results on GHA Workflow summary

gradle.properties
=> Opt-in for precise resource shrinking

app/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/conventions/AndroidModuleConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/conventions/SecurityConventions.kt
=> Conditionally adding LeakCanary on release APKs

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/conventions/SecurityConventions.kt
=> Improving build logs when running security logs

.github/workflows/main.yml
=> Scanning source file with trufflehog

features/facts/src/main/AndroidManifest.xml, features/search/src/main/AndroidManifest.xml
=> Dont export internal Activities

.github/workflows/main.yml
=> Adds Gradle wrapper Security check at CI time

features/facts/src/test/java/io/dotanuki/norris/facts/FactsActivityTests.kt, features/search/src/test/java/io/dotanuki/norris/search/SearchActivityTests.kt, features/search/src/test/java/io/dotanuki/norris/search/SearchDataSourceTests.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/AndroidDefinitions.kt, platform/android/core-navigator/src/test/java/io/dotanuki/norris/navigator/NavigatorTests.kt
=> Bumps target Android SDK to v33

.github/actions/setup-android-build/action.yml, .github/actions/setup-android-build/normalize-jdk-version.sh, .github/workflows/main.yml
Covering more platform integration by exercising builds against JDK17
N/A
=> Running builds against jdk17 for some GHA jobs

.github/actions/setup-android-build/action.yml
=> Bumps actions/setup-java to 3.5.0

.github/workflows/main.yml, build.gradle.kts, gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/FeatureMatrixPlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/FeatureMatrixTask.kt
=> Evaluates feature modules dynamically during GHA workflow

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/FeatureMatrixTask.kt
=> Makes featureMatrix task cacheable

.github/workflows/main.yml, build.gradle.kts, gradle/libs.versions.toml, gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/AutoModulePlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/internal/conventions/AndroidModuleConventions.kt
Adds [ruler](https://github.com/spotify/ruler) to this project and stores reports as CI artifacts
N/A
=> Analysing app size with Ruler plugin

.mergify.yml
=> Updates mergify configuration

gradle/libs.versions.toml, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/SecurityChecksPlugin.kt
Closes #662
Required since there was a breaking change in this version (package/import for `Component.Type` enum)
=> Bumps oss-gradle-scan plugin to v2.5.0

.github/workflows/main.yml
Self-explained. We already have the same insights on top of Foresight
=> Ditches test-summary GHA from CI pipeline

build.gradle.kts
=> Ditches unused Maven repo from buildscript

gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/features/FeatureMatrixPlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/features/FeatureMatrixTask.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/AutoModulePlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidModuleConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/KotlinModuleConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/TestLoggingConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/AppVersion.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/ModuleConvention.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/PlatformDefinitions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/ProguardRules.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/Versioning.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/security/SecurityChecksPlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/security/SecurityConventions.kt
Makes things easier to find by grouping proper files
N/A
=> Re-organizes internal Gradle plugins

app/proguard/assets.pro, app/src/androidTest/java/io/dotanuki/demos/norris/test/ScreenRobot.kt, app/src/main/AndroidManifest.xml, app/src/main/java/io/dotanuki/demos/norris/SplashActivity.kt, app/src/main/java/io/dotanuki/demos/norris/di/applicationModule.kt, features/facts/src/androidTest/AndroidManifest.xml, features/facts/src/androidTest/java/io/dotanuki/norris/facts/test/FactsScreenshotTests.kt, features/facts/src/main/AndroidManifest.xml, features/facts/src/main/java/io/dotanuki/norris/facts/presentation/ErrorStateResources.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsRecyclerAdapter.kt, features/facts/src/main/java/io/dotanuki/norris/facts/ui/FactsView.kt, features/facts/src/test/java/io/dotanuki/norris/facts/FactsActivityTests.kt, features/search/src/androidTest/AndroidManifest.xml, features/search/src/androidTest/java/io/dotanuki/norris/search/test/SearchScreenshotTests.kt, features/search/src/main/AndroidManifest.xml, features/search/src/main/java/io/dotanuki/norris/search/ui/SearchView.kt, features/search/src/test/java/io/dotanuki/norris/search/SearchActivityTests.kt, gradle.properties, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidModuleConventions.kt, platform/android/core-assets/src/main/AndroidManifest.xml, platform/android/core-helpers/src/main/AndroidManifest.xml, platform/android/core-navigator/src/main/AndroidManifest.xml, platform/android/core-persistance/src/main/AndroidManifest.xml, platform/android/testing-app/src/main/AndroidManifest.xml, platform/android/testing-persistance/src/main/AndroidManifest.xml, platform/android/testing-screenshots/src/main/AndroidManifest.xml
Follow-up of #664 
Normalisation of packages according namespaces to follow
=> Adopts convention namespace for all Android modules

.github/workflows/main.yml
Building only the needed test APKs rather than the all ones
=> Reworks espress-prepare inside CI workflow

.github/workflows/main.yml
=> Reworks GHA workflow topology

.github/workflows/main.yml
=> Adds retries over MobSF report generation

.github/workflows/main.yml
Simplify the CI pipeline by building all instrumentation artifacts in a single Job
Follow-up #707
=> Dont run features-lookup in CI anymore

.github/actions/setup-android-build/action.yml, .github/workflows/main.yml
=> Bumps actions/setup-java to 3.6.0

.github/actions/setup-android-build/action.yml
=> Improves execution of gradle-build-cache Action

.github/workflows/main.yml, .maestro/acceptance.yaml, .maestro/config.yaml, scripts/maestro-run.sh
Replaces current white-box acceptance tests with a black-box e2e combine one
Trying with [maestro.mobile.dev](https://maestro.mobile.dev/) for now
=> Running e2e tests with maestro cloud

.github/workflows/main.yml
=> Bumps actions/download-artifact to v3.0.1

.maestro/acceptance.yaml, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidModuleConventions.kt
=> Renames applicationIds on target binaries

.github/workflows/main.yml, scripts/maestro-run.sh
Adds flexibility to `maestro-run.sh` so it can be used both locally and on CI machines in the same way
N/A
=> Revamps maestro companion script with runner detection

.github/workflows/main.yml, app/src/androidTest/java/io/dotanuki/app/NorrisAcceptanceTests.kt, app/src/androidTest/java/io/dotanuki/app/ScreenRobot.kt
=> Re-enables white-box acceptance tests

.editorconfig, .github/workflows/main.yml, scripts/aggregate-test-reports.sh, scripts/code-style-bash.sh, scripts/code-style-kotlin.sh, scripts/maestro-run.sh
=> Adds code style checker for Bash scripts

scripts/code-style-kotlin.sh
=> Bumps detekt to 1.22.0

.editorconfig, app/src/main/java/io/dotanuki/app/SplashActivity.kt, scripts/code-style-kotlin.sh
=> Bumps ktlint to v0.48.1

.github/renovate.json
=> Enables dependency dashboard on Renovate

.github/actions/setup-android-build/setup-gradle-properties.sh, gradle.properties
=> Capturing stacktraces from Gradle failures by default

.github/workflows/main.yml
=> Enforces e2e execution before crunching test results

README.md
=> Improves table rendering

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/KotlinModuleConventions.kt
Follow-up of #792 
Prepares the stage for Gradle 8.0.x
=> Clears more build-logic warnings

platform.properties
=> Bumps android-build-tools to 33.0.2

README.md
=> Updates README highlightinig some used tools

README.md
=> Fixes link

README.md
=> Replaces Twitter with Mastodon profile

gradle/wrapper/gradle-wrapper.properties
=> Bumps Gradle distribution to 7.6.1

.github/renovate.json
=> Enables OSS vulnerabilities alerts driven by Renovate

.github/actions/setup-android-build/action.yml, .github/actions/setup-android-build/setup-android-keystore.sh, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidModuleConventions.kt
Simpler build process by not requiring the "oficial" keystore to sign a release build
`age` will be eventually removed in an upcoming PR
=> Signing release variants with debug keystore

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/security/SecurityConventions.kt
=> Improves warning regarding non-blocking CVEs

app/src/main/java/io/dotanuki/app/DependenciesSetup.kt, features/facts/src/main/java/io/dotanuki/features/facts/data/FactsDataSource.kt, features/search/src/main/java/io/dotanuki/features/search/data/SearchesDataSource.kt, platform/android/testing-app/src/main/java/io/dotanuki/platform/android/testing/app/TestApplication.kt, platform/jvm/core-networking/src/main/java/io/dotanuki/platform/jvm/core/networking/ManagedExecution.kt, platform/jvm/core-networking/src/test/java/io/dotanuki/platform/jvm/core/networking/ManagedExecutionTests.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisService.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/RestServiceModule.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/ChuckNorrisApi.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/MockWebServerExtensions.kt
=> Improves convention names for network-related abstractions

.github/actions/setup-android-build/action.yml, .github/workflows/main.yml, .tool-versions, scripts/code-style-kotlin.sh, scripts/setup-asdf.sh
=> Managing detekt version with asdf

.github/actions/setup-android-build/action.yml, .github/workflows/main.yml
=> Removes requirement on previous signing key from GHA pipeline

.github/workflows/main.yml, .tool-versions, scripts/maestro.sh, scripts/setup-asdf.sh
=> Managing maestro versions with asdf

.github/workflows/main.yml, .tool-versions, scripts/emulator-wtf.sh, scripts/setup-asdf.sh
=> Moving ew-cli management to asdf

app/src/main/java/io/dotanuki/app/di/ApplicationModule.kt
=> Updates mock-server url

functional-tests/acceptance.yaml
=> Taking screenshots during functional tests

scripts/maestro.sh
=> Improves maestro script

.github/actions/setup-android-build/setup-gradle-properties.sh, gradle.properties
=> Cleaning up Gradle flags

.github/workflows/main.yml
=> Driving app-size analysis with emerge-tools

platform.properties
=> Bumps Android minsdk to 26

platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/RetrofitBuilder.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilienceConfiguration.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilientExecution.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/RestInfrastructureRule.kt
=> Implements timeouts for HTTP requests

gradle/libs.versions.toml, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/security/SecurityConventions.kt, platform/jvm/core-networking/src/main/java/io/dotanuki/platform/jvm/core/networking/transformers/NetworkConnectivityErrorTransformer.kt, platform/jvm/core-rest/build.gradle.kts, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClient.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/RetrofitBuilder.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/RestServiceModule.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilienceConfiguration.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilientExecution.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/util/ToxicityLevel.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/util/ToxyProxyExtensions.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/RestInfrastructureTestModule.kt
=> Adds HTTP resilience tests on top of toxyproxy

features/facts/src/test/java/io/dotanuki/features/facts/FactsDataSourceTests.kt, features/search/src/test/java/io/dotanuki/features/search/SearchDataSourceTests.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/security/SecurityConventions.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClient.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/HttpResilience.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/RetrofitBuilder.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/RestServiceModule.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilientExecution.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/FakeHttpResilience.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/RestInfrastructureTestModule.kt
=> Improves legibility of HTTP resilience tests

platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/RetrofitBuilder.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/RestInfrastructureRule.kt
=> Cleaning-up cluttering from HTTP layer

.github/workflows/main.yml
Since Foresight will sunset soon, we'll replace it with a temporary solution
N/A
=> Replaces tool to analyse test reports

.github/workflows/main.yml
=> Fixes GHA workflow permissions

features/facts/src/main/java/io/dotanuki/features/facts/ui/FactsActivity.kt, features/facts/src/main/java/io/dotanuki/features/facts/ui/FactsEventsHandler.kt, features/search/src/main/java/io/dotanuki/features/search/ui/SearchActivity.kt, features/search/src/main/java/io/dotanuki/features/search/ui/SearchEventsHandler.kt
=> Cleaning-up handlers on Activities

app/src/androidTest/java/io/dotanuki/app/NorrisAcceptanceTests.kt, features/facts/src/test/java/io/dotanuki/features/facts/presentation/FactsViewModelTests.kt, features/search/src/test/java/io/dotanuki/features/search/data/SearchDataSourceTests.kt, features/search/src/test/java/io/dotanuki/features/search/presentation/SearchViewModelTests.kt, platform/android/testing-persistance/src/main/java/io/dotanuki/platform/android/testing/persistance/StorageTestHelper.kt
=> Simplyfing tests with StorageTestHelper

build.gradle.kts, gradle/libs.versions.toml, gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/AutoModulePlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidModuleConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/KotlinModuleConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/TestConventions.kt
=> Improves integration tests with gradle-test-retry plugin

build.gradle.kts, gradle/libs.versions.toml, gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidModuleConventions.kt
=> Removes keeper plugin

app/src/main/java/io/dotanuki/app/di/NorrisApiUrlFactory.kt, app/src/main/java/io/dotanuki/app/di/NorrisAppComponentFactory.kt, features/facts/src/main/java/io/dotanuki/features/facts/di/FactsActivityFactory.kt, features/facts/src/main/java/io/dotanuki/features/facts/di/FactsViewModelFactory.kt, features/facts/src/main/java/io/dotanuki/features/facts/ui/FactsActivity.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchActivityFactory.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchViewModelFactory.kt, features/search/src/main/java/io/dotanuki/features/search/ui/SearchActivity.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/KotlinModuleConventions.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/ApiUrlFactory.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/ChuckNorrisServiceClientFactory.kt
=> Driving IoC with Kotlin context receivers

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/security/SecurityConventions.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt
As per https://github.com/testcontainers/testcontainers-java/issues/6647
Hopefully this fixes a couple of container startup issues we face, especially in the localhost
=> Using custom Wait strategy for MockServer container

app/src/main/java/io/dotanuki/app/di/NorrisApiUrlFactory.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceBuilder.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/ApiUrlFactory.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/ChuckNorrisServiceClientFactory.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilientExecution.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt
=> Improves legibility with ServiceBuilder convention

app/src/main/java/io/dotanuki/app/di/NorrisApiUrlFactory.kt
=> Changes mock-server endpoint

features/facts/src/androidTest/java/io/dotanuki/features/facts/FactsScreenshotTests.kt, features/facts/src/androidTest/java/io/dotanuki/features/facts/util/FactsScreenshotsDriver.kt, features/search/src/androidTest/java/io/dotanuki/features/search/SearchScreenshotTests.kt, features/search/src/androidTest/java/io/dotanuki/features/search/util/SearchScreenshotsDriver.kt
=> Extracts screenshot test drivers

build.gradle.kts, gradle/libs.versions.toml, gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/AutoModulePlugin.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/TestConventions.kt
=> Removes test-retry plugin

features/facts/build.gradle.kts, features/search/build.gradle.kts, gradle/libs.versions.toml, platform/jvm/core-rest/build.gradle.kts, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/util/WireMockContainer.kt, platform/jvm/testing-rest/build.gradle.kts
=> Removes unused dependencies

platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/internal/ResilienceAwareExecution.kt
=> Fixes wrong name

README.md
=> Links another blog post

.github/renovate.json, gradle/wrapper/gradle-wrapper.properties
=> Enables Gradle distro upgrades with Renovate

platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt
=> Improves test setup

scripts/code-style-kotlin.sh
=> Fixes linting scripts

.github/workflows/main.yml, features/facts/src/main/java/io/dotanuki/features/facts/di/FactsActivityFactory.kt, features/facts/src/main/java/io/dotanuki/features/facts/di/FactsViewModelFactory.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchActivityFactory.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchViewModelFactory.kt, platform/android/core-persistance/src/main/java/io/dotanuki/platform/android/core/persistance/di/LocalStorageFactory.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/ChuckNorrisServiceClientFactory.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt
=> Simpler usage of Kotlin context receivers

.github/renovate.json
=> Enables automatic updates for asdf-managed tooling

platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/ChuckNorrisServiceClientTests.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/util/ToxicityLevel.kt
=> Decreases toxicity level used in integration tests

features/facts/src/androidTest/java/io/dotanuki/features/facts/FactsScreenshotTests.kt, features/search/src/androidTest/java/io/dotanuki/features/search/SearchScreenshotTests.kt, platform/android/testing-screenshots/src/main/java/io/dotanuki/platform/android/testing/screenshots/ScreenshotMatcher.kt
=> Improves screenshot tests

features/facts/src/androidTest/java/io/dotanuki/features/facts/FactsAcceptanceTests.kt, features/facts/src/test/java/io/dotanuki/features/facts/presentation/FactsViewModelTests.kt, features/search/src/androidTest/java/io/dotanuki/features/search/SearchAcceptanceTests.kt, features/search/src/test/java/io/dotanuki/features/search/presentation/SearchViewModelTests.kt, platform/android/core-persistance/src/main/java/io/dotanuki/platform/android/core/persistance/LocalStorage.kt, platform/android/core-persistance/src/test/java/io/dotanuki/platform/android/core/persistance/LocalStorageTests.kt, platform/android/testing-helpers/src/main/java/io/dotanuki/platform/android/testing/helpers/PrettyEspressoTraces.kt, platform/android/testing-persistance/src/main/java/io/dotanuki/platform/android/testing/persistance/StorageTestHelper.kt
=> Improves instrumentation tests

features/facts/src/main/java/io/dotanuki/features/facts/di/FactsActivityFactory.kt, features/facts/src/main/java/io/dotanuki/features/facts/di/FactsContext.kt, features/facts/src/main/java/io/dotanuki/features/facts/di/FactsViewModelFactory.kt, features/facts/src/test/java/io/dotanuki/features/facts/presentation/FactsViewModelTests.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchActivityFactory.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchContext.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchViewModelFactory.kt, features/search/src/test/java/io/dotanuki/features/search/presentation/SearchViewModelTests.kt
=> Improves receivers contexts and ViewModel tests

features/facts/src/main/java/io/dotanuki/features/facts/presentation/FactsStateMachine.kt, features/facts/src/main/java/io/dotanuki/features/facts/presentation/FactsViewModel.kt, features/search/src/main/java/io/dotanuki/features/search/presentation/SearchStateMachine.kt, features/search/src/main/java/io/dotanuki/features/search/presentation/SearchViewModel.kt
=> Extracts state machines from ViewModels

features/facts/src/main/java/io/dotanuki/features/facts/di/FactsContext.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchContext.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/RestClient.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/ChuckNorrisServiceClientFactory.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/RestClientTests.kt, platform/jvm/testing-rest/src/main/java/io/dotanuki/platform/jvm/testing/rest/RestTestHelper.kt
=> Renames Rest client

features/facts/src/main/java/io/dotanuki/features/facts/di/FactsContext.kt, features/search/src/main/java/io/dotanuki/features/search/di/SearchContext.kt, platform/jvm/core-rest/src/main/java/io/dotanuki/platform/jvm/core/rest/di/RestClientFactory.kt
=> Renames factory

README.md
=> Links post blog on Kotlin Context Receivers

.github/dependabot.yml, .github/renovate.json
=> Using Renovate to update all dependencies

.github/workflows/main.yml
=> Changing approach for SBOMs

.github/workflows/main.yml, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/util/ToxicityLevel.kt
=> Improves tests

app/src/main/java/io/dotanuki/app/SplashActivity.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidStandardConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/PlatformDefinitions.kt, platform.properties
=> Bumps android-compile-sdk to 34

gradle.properties, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/KotlinConventions.kt
Self-explained
https://kotlinlang.org/docs/whatsnew19.html#try-the-k2-compiler-in-your-project
=> Trying out k2 compiler

gradle.properties
Self-explained
https://medium.com/androiddevelopers/5-ways-to-prepare-your-app-build-for-android-studio-flamingo-release-da34616bb946
=> Enables buildconfig as bytecode

.github/actions/setup-android-build/action.yml
=> Enables GH deps submission via gradle-build-action

gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/KotlinConventions.kt, platform.properties
Hint about `-Xstring-concat=inline` courtesy of https://github.com/Kotlin/kotlinx.serialization/issues/2145
=> Targeting java11 byte code by default

.github/actions/setup-monitoring/action.yml, .github/workflows/main.yml
=> Monitoring networking activity on GHA workflows

gradle/wrapper/gradle-wrapper.properties
=> Tracks distribution checksum for the Gradle distribution

.github/actions/setup-android-build/action.yml, .github/actions/setup-android-build/setup-android-keystore.sh, .github/actions/setup-android-build/setup-gradle-properties.sh, .github/workflows/main.yml, app/src/main/java/io/dotanuki/app/di/NorrisApiUrlFactory.kt, platform/jvm/testing-mockserver/src/main/java/io/dotanuki/platform/jvm/testing/mockserver/MockServerUrlFactory.kt
=> Updates fake server URL and tooling

.github/workflows/main.yml
=> Removes useless CI step

app/build.gradle.kts, gradle/libs.versions.toml, platform/jvm/core-rest/build.gradle.kts, platform/jvm/testing-rest/build.gradle.kts
=> Enforcing okio transitive dependency version

README.md
=> Fixes link to GHA badge

scripts/setup-asdf.sh
=> Cleans asdf setup script

.github/workflows/main.yml, .mergify.yml
=> Analyses app size only on master branch builds

.github/workflows/main.yml
=> Updates appsweep GHA inputs

.config/norris-watchdog.toml, .github/workflows/main.yml, .tool-versions, scripts/setup-asdf.sh
=> Adds watchdog for release archives

.github/actions/setup-android-build/action.yml, .github/workflows/main.yml, settings.gradle.kts
=> Enables builds with Gradle build scan

.tool-versions
https://github.com/dotanuki-labs/android-archives-watchdog/releases/tag/0.2.0
=> Updates aaw to v0.2.0

.github/workflows/main.yml
- Closes #1181 
- Closes #1182 
N/A
=> Updates download and upload actions to v4.x

.github/actions/setup-android-build/setup-gradle-properties.sh, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/RestClientTests.kt, platform/jvm/core-rest/src/test/java/io/dotanuki/platform/jvm/core/rest/util/ToxicityLevel.kt
=> Updates spec for new Linux GHA runners

gradle/libs.versions.toml, gradle/plugins/build.gradle.kts, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidApplicationConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidFeatureLibraryConventions.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/PlatformDefinitions.kt, platform.properties
=> Enables builds targeting jdk17 bytecode

.github/actions/setup-android-build/action.yml, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/models/PlatformDefinitions.kt, platform.properties
=> Running builds against JDK21

gradle.properties, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/features/FeatureMatrixTask.kt, gradle/plugins/src/main/kotlin/io/dotanuki/norris/gradle/modules/conventions/AndroidApplicationConventions.kt
=> Cleanup deprecations after AGP 8.x.y

.github/actions/setup-android-build/action.yml
=> Uses new gradle/actions on CI

.github/workflows/main.yml, gradle.properties, settings.gradle.kts
=> Cleaning up Gradle config

.github/workflows/main.yml
=> Fix CI checks

.github/workflows/main.yml
=> Fixes appsweep integration

.github/workflows/main.yml
=> Using dotanuki-labs/appsweep-scan-action on CI

platform.properties
=> Adds android-35 targets
